name: trivy

on:
  push:
    branches: master

# env:
#   TRIVY_RESULTS: ""

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: trivy scan
      id: trivy_scan 
      run: |
        export TRIVY_VERSION=$(wget -qO - "https://api.github.com/repos/aquasecurity/trivy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        wget --no-verbose https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -O - | tar -zxvf -
        ./trivy image httpd:2.2-alpine > $RUNNER_WORKSPACE/trivy_results.out
        echo ::set-output name=TRIVY_RESULTS::$(cat $RUNNER_WORKSPACE/trivy_results.out | grep Total:)
    - name: show file
      run: |
        echo "Trivy Results"
        echo "-------------"
        cat $RUNNER_WORKSPACE/trivy_results.out | grep Total: 
    - if: always()
      name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: trivy report
        path: "${RUNNER_WORKSPACE}/trivy_results.out"
#     - name: print result
#       env:
#         TRIVY_RESULTS: ${{ steps.trivy_scan.outputs.TRIVY_RESULTS }}
#       run: echo $TRIVY_RESULTS
      
        
